### ISSUE TITLE
H5 data type issue

### ISSUE THREAD

**Issue by pabloriera** [moble/out_of_core_fft#1]
Hi, I am trying to do FFT on WAV files on disk, so I tried to put creat H5 files from the wav data and then make the FFT. I am not sure if the problem is with the H5 file creation or is a bug.

By the way, do you know another way to do FFT on WAV files from disk without moving them to RAM?

Thanks

```python
def wavread(file_name):
    from scipy.io.wavfile import read
    fs, y = read(file_name)
    return fs,np.array(y,dtype=np.float64)/(2**15-1)

def power_two(n):
    return int(np.ceil(np.log2(n)))

fs,s = wavread('out.wav')
x = np.zeros(2**power_two(s.shape[0]))
x[:s.shape[0]]=s[:,0]

fp = h5py.File('input.h5','w',)
gr = fp.create_group('x')
gr.create_dataset('x',data=x,shape=x.shape)
fp.close()

out_of_core_fft.fft('input.h5', 'x', 'output.h5', 'X')

Exception ignored in: 'h5py._proxy.make_reduced_type'
ValueError: Cannot return member number (Operation not supported for type class)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-54c55743fa99> in <module>()
----> 1 out_of_core_fft.fft('input.h5', 'x', 'output.h5', 'X')

/usr/local/lib/python3.5/dist-packages/out_of_core_fft/__init__.py in fft(*args, **kwargs)
    403 def fft(*args, **kwargs):
    404     kwargs['inverse_fft'] = False
--> 405     _general_fft(*args, **kwargs)
    406 fft.__doc__ = "Perform FFT for very large dataset stored in HDF5 file" + _general_fft.__doc__

/usr/local/lib/python3.5/dist-packages/out_of_core_fft/__init__.py in _general_fft(infile, ingroup, outfile, outgroup, overwrite, mem_limit, inverse_fft, show_progress)
    345                 if show_progress and k % max(C//20, 20) == 1:
    346                     print("\t\t\t{0} of {1}".format(k, C))
--> 347                 y[k] = np.exp(np.arange(R)*(-k*2j*np.pi/N)) * np.fft.fft(y[k])
    348 
    349         # Step 4:

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2840)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2798)()

/usr/local/lib/python3.5/dist-packages/h5py/_hl/dataset.py in __setitem__(self, args, val)
    628         mspace = h5s.create_simple(mshape_pad, (h5s.UNLIMITED,)*len(mshape_pad))
    629         for fspace in selection.broadcast(mshape):
--> 630             self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
    631 
    632     def read_direct(self, dest, source_sel=None, dest_sel=None):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2840)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2798)()

h5py/h5d.pyx in h5py.h5d.DatasetID.write (/tmp/pip-huypgcah-build/h5py/h5d.c:3694)()

h5py/_proxy.pyx in h5py._proxy.dset_rw (/tmp/pip-huypgcah-build/h5py/_proxy.c:1971)()

h5py/_proxy.pyx in h5py._proxy.needs_proxy (/tmp/pip-huypgcah-build/h5py/_proxy.c:3964)()

ValueError: Not a datatype (Not a datatype)

```

**Comment by moble** [comment]
I should probably catch this error, but the problem is simply that this module is written for complex functions.  A workaround would be to simply define `x` to have complex `dtype`; the imaginary parts should automatically get set to zero.  The on-disk data will be twice as large as they need to be in principle, but it would take a lot of work to write and test a function that works on real data only.  Pull requests are welcome!

> By the way, do you know another way to do FFT on WAV files from disk without moving them to RAM?

I'm not sure I understand your question.  There's presumably no such disk that would allow you to do an FFT without moving the data off of the disk.  If you're talking about something other than RAM, I guess you mean processor cache.  I honestly don't know if this is possible, but it seems conceivable that HDF5 might support some fancy thing where the data is moved directly from disk to the processor cache, bypassing the RAM.  If there is such a thing, and it's supported by h5py, it should be easy to change this module to support it, but I don't know anything about it.

**Comment by pabloriera** [comment]
Ok, thanks a lot! I will try the complex `dtype` it should not make any difference. 

I asked the second question because I thought the problem was with hdf5, so maybe there was another way using the raw WAV. I don't know if, in general, there is a need for doing FFT on large WAV files, but maybe it was a thing.

**Comment by moble** [comment]
> I asked the second question because I thought the problem was with hdf5, so maybe there was another way using the raw WAV. I don't know if, in general, there is a need for doing FFT on large WAV files, but maybe it was a thing.

Oh, I see.  I didn't get that you were talking about WAV as opposed to HDF5.  It would be the same principle, alright.  There's nothing special about HDF5 — except that it's what I happen to use, and there's a nice interface for just reading parts of the file.  It looks like `scipy.io.wavfile.read` has an `mmap` option that would do something similar, so it might be pretty easy to rewrite the functions in this module to deal with WAV.  That, of course, would also be a good chance to write a function just for real data.  I've got newborn twins at home, though, so I don't expect to have any time to do that within the next 18 years or so...  :)

**Comment by pabloriera** [comment]
Haha! congratulations! 18 years, you are been optimistic...
I could easily try to add the real data feature but casting it to complex, If I success I will pull it... Thanks again.
